### ISSUE TITLE
TXPO cannot be displayed correctly in OLS

### ISSUE THREAD

**Issue by matentzn** [txpo-ontology/TXPO#1]
Hey, I know fixing this can be a bit of a pain, but because TXPO is cyclic, it cannot be displayed properly in OLS, see here:

https://github.com/EBISPOT/OLS/issues/310

You should prioritise fixing these, if you want TXPO indexed in OLS!

**Comment by txpo-ontology** [comment]
Thank you for reporting.
Could you check again whether the latest version shows the cyclic?
It seems all URIs are relations (object properties).
I developed this ontology by Protege, and it seems that there is no cyclic in the object property hierarchy.
For example, about TXPO:0002523, the term usage tab in Protege desktop shows only its lower sub-properties.

**Comment by jamesamcl** [comment]
The issue is actually in the annotation properties:

    
    <owl:AnnotationProperty rdf:about=“http://www.w3.org/2004/02/skos/core#altLabel”>
        <rdfs:subPropertyOf rdf:resource=“http://www.w3.org/2004/02/skos/core#altLabel”/>
    </owl:AnnotationProperty>

**Comment by txpo-ontology** [comment]
Thank you! I deleted the annotation property altLabel, and updated txpo.owl.
https://github.com/txpo-ontology/TXPO/blob/master/txpo.owl
