### ISSUE TITLE
There are 248 unsatisfiable classes in TXPO

### ISSUE THREAD

**Issue by dillerm** [txpo-ontology/TXPO#5]
I ran the HermiT reasoner on TXPO and it identified 248 unsatisfiable classes. The attached Excel file contains each of them.

[unsatisfiable_classes_txpo.xlsx](https://github.com/txpo-ontology/TXPO/files/9998190/unsatisfiable_classes_txpo.xlsx)

**Comment by txpo-ontology** [comment]
Hi @dillerm, thank you for your report. I removed the inconsistency and rechecked with HermiT.
I uploaded the revised version of txpo.owl

**Comment by dillerm** [comment]
Everything looks good on my end!
